import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { runLogoRuntime, validateLogoBenchmark } from '../lib/logo-runtime.mjs';
import { LOGO_TYPES } from '../modules/logo/runtime.mjs';
import { buildLogoPsychology, PSYCHOLOGY_DIMENSIONS } from '../modules/logo-psychology/runtime.mjs';
import { buildLogoInspirationPacket, LOGO_INSPIRATION_SOURCES } from '../modules/logo-inspiration/runtime.mjs';
import { validateLogoIntegrity } from '../modules/logo-integrity/runtime.mjs';

const input = JSON.parse(fs.readFileSync(new URL('../benchmarks/006-logo-identity/input.json', import.meta.url)));
const expected = JSON.parse(fs.readFileSync(new URL('../benchmarks/006-logo-identity/expected.json', import.meta.url)));

test('covers seven canonical logo types', () => assert.equal(LOGO_TYPES.length, 7));
test('benchmark passes', () => { const output = runLogoRuntime(input); assert.equal(output.status, 'approved'); assert.deepEqual(validateLogoBenchmark(output, expected), { pass:true, failures:[] }); });
test('missing any logo type blocks', () => { const b=structuredClone(input); b.typeAssessments.pop(); assert.equal(runLogoRuntime(b).status,'blocked'); });
test('universal color myth blocks', () => { const b=structuredClone(input.psychology); b.hypotheses.find(x=>x.dimension==='color-context').intendedEffect='Blue always means trust'; assert.equal(buildLogoPsychology(b).status,'blocked'); });
test('psychology requires evidence and falsifier', () => { const b=structuredClone(input.psychology); b.hypotheses[0].falsifier=''; b.hypotheses[1].evidenceBasis=''; assert(buildLogoPsychology(b).findings.length>=2); });
test('exact copying from inspiration blocks', () => { const r=buildLogoInspirationPacket({references:[{id:'x',reference:'x',sourceId:'logolounge',evidence:'e',take:'copy exact logo',reject:'none',transform:'copy exact'}]}); assert.equal(r.status,'blocked'); });
test('four requested inspiration sites are first-class sources', () => assert.deepEqual(LOGO_INSPIRATION_SOURCES.map(x=>x.id), ['logolounge','logosystem','logomoose','inspirationlogo']));
test('psychology goes beyond color and shape', () => { assert(PSYCHOLOGY_DIMENSIONS.includes('processing-fluency')); assert(PSYCHOLOGY_DIMENSIONS.includes('figure-ground')); assert(PSYCHOLOGY_DIMENSIONS.includes('distinctiveness-familiarity')); });
test('raster final master blocks', () => { const b=structuredClone(input); b.system.finalAssetFormat='raster'; b.system.vectorRequired=false; assert.equal(runLogoRuntime(b).status,'blocked'); });
test('missing responsive micro mark blocks', () => { const b=structuredClone(input); delete b.system.responsive.microMark; assert.equal(runLogoRuntime(b).status,'blocked'); });
test('small-size failure blocks', () => { const b=structuredClone(input); b.system.stressTests['16px']='fail'; assert.equal(runLogoRuntime(b).status,'blocked'); });
test('high AI-generic risk blocks', () => { const b=structuredClone(input); b.system.qa.aiGenericRisk=7; assert.equal(runLogoRuntime(b).status,'blocked'); });
test('originality review mandatory', () => { const b=structuredClone(input); b.system.originalityReview.status='pending'; assert.equal(runLogoRuntime(b).status,'blocked'); });
test('shape geometry drift blocks', () => { const b=structuredClone(input.integrity); b.exported.shapes[0].geometryFingerprint='sha256:changed'; assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('SVG palette drift blocks', () => { const b=structuredClone(input.integrity); b.exported.palette[1].value='#FFFFFF'; assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('raw SVG color drift blocks', () => { const b=structuredClone(input.integrity); b.exported.svg.rawColors.push('#00FF00'); assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('layer order drift blocks', () => { const b=structuredClone(input.integrity); b.exported.layers[1].zIndex=0; assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('shape-to-layer drift blocks', () => { const b=structuredClone(input.integrity); b.exported.shapes[1].layerId='base'; assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('overlap geometry drift blocks', () => { const b=structuredClone(input.integrity); b.exported.overlaps[0].areaRatio=0.12; assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('unexpected overlap blocks', () => { const b=structuredClone(input.integrity); b.exported.unexpectedOverlapCount=1; assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('layer occlusion violation blocks', () => { const b=structuredClone(input.integrity); b.exported.layerOcclusionViolations=1; assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('render drift blocks', () => { const b=structuredClone(input.integrity); b.exported.renderEvidence.find(x=>x.size===16).visualDiffPct=3; assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('missing render diff evidence blocks', () => { const b=structuredClone(input.integrity); b.exported.renderEvidence=b.exported.renderEvidence.filter(x=>x.size!==32); assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('viewBox drift blocks', () => { const b=structuredClone(input.integrity); b.exported.viewBox=[0,0,1200,1000]; assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('embedded raster blocks SVG master', () => { const b=structuredClone(input.integrity); b.exported.svg.embeddedRaster=true; assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('multi-layer mark must declare layers', () => { const b=structuredClone(input.integrity); b.canonical.layered=false; assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('missing actual SVG hash evidence blocks', () => { const b=structuredClone(input.integrity); b.exported.svg.fileSha256=''; assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('missing SVG inspector evidence blocks', () => { const b=structuredClone(input.integrity); b.exported.svg.inspectorEvidence=''; assert.equal(validateLogoIntegrity(b).status,'blocked'); });
test('integrity reports locks separately', () => { const b=structuredClone(input.integrity); b.exported.layers[0].opacity=.5; const result=validateLogoIntegrity(b); assert.equal(result.locks.layers.status,'blocked'); assert.equal(result.locks.shape.status,'locked'); });
