import { buildCreativeIntelligenceFoundation } from '../creative-intelligence-foundation/runtime.mjs';

const CAPTURED_AT = '2026-08-28T00:00:00Z';

function principle({
  id,
  title,
  definition,
  causalRationale,
  perceptualEffects,
  worksWhen,
  failsWhen,
  creativeVariables,
  failureModes,
  counterexamples,
  diagnostics,
  transferablePrinciples,
  adaptationRules,
  copyRisks,
  crossDomainApplications = ['product interaction', 'brand motion', 'editorial motion', 'spatial interfaces'],
  confidence = 0.9,
  confidenceBasis = 'Curated motion-design principle with explicit causal rationale, boundary conditions, failure modes and diagnostics.'
}) {
  return {
    id,
    kind: 'principle',
    domain: 'motion',
    title,
    definition,
    causalRationale,
    perceptualEffects,
    worksWhen,
    failsWhen,
    creativeVariables,
    crossDomainApplications,
    failureModes,
    counterexamples,
    diagnostics,
    relationships: [],
    provenance: {
      sourceId: `motion-v2:${id}`,
      sourceType: 'curated-motion-principle',
      sourceRef: '',
      capturedAt: CAPTURED_AT,
      author: 'AI Studio OS',
      notes: 'Motion Intelligence V2 internal qualified knowledge corpus.'
    },
    confidence,
    confidenceBasis,
    scope: 'general',
    transferability: 'Transfer the causal temporal/perceptual principle, then rebuild expression for the project, interaction, medium, viewport and accessibility constraints.',
    transfer: {
      transferablePrinciples,
      surfaceSignature: [],
      mustStrip: [],
      adaptationRules,
      copyRisks
    },
    notes: ['Evidence for reasoning only; never a motion direction, winner, implementation recipe or production approval.']
  };
}

export const MOTION_INTELLIGENCE_V2_KNOWLEDGE = Object.freeze([
  principle({
    id: 'motion-necessity',
    title: 'Motion must earn temporal change',
    definition: 'Movement should exist only when change over time communicates something that a stable state cannot communicate as clearly.',
    causalRationale: 'Motion automatically competes for attention. When temporal change corresponds to state, hierarchy, causality or orientation it can reduce inference; when it does not, it spends attention without adding meaning.',
    perceptualEffects: ['clear relationship between motion and consequence', 'lower decorative noise', 'stronger contrast between meaningful change and stillness'],
    worksWhen: ['state changes need to be perceived', 'causal relationships unfold over time', 'continuity or spatial orientation must be preserved'],
    failsWhen: ['the same meaning is clearer in a stable state', 'movement exists primarily to signal premium aesthetics', 'frequent low-value changes consume attention'],
    creativeVariables: ['event significance', 'motion frequency', 'motion amplitude', 'stillness duration', 'semantic gain'],
    failureModes: ['ambient motion becomes visual debt', 'minor events inherit major motion weight', 'motion competes with reading'],
    counterexamples: ['a dense comparison surface where simultaneous stable inspection is the primary task'],
    diagnostics: ['remove the motion and ask what product meaning becomes materially harder to perceive', 'compare attention cost against semantic gain'],
    transferablePrinciples: ['movement must earn its attention cost through temporal meaning'],
    adaptationRules: ['tie motion permission to product consequence, causal change, orientation or hierarchy rather than decoration'],
    copyRisks: ['turning a significance gate into a universal animation checklist']
  }),
  principle({
    id: 'attention-handoff',
    title: 'Attention should be handed off, not scattered',
    definition: 'Temporal composition should deliberately move perceptual priority from one meaningful target to the next.',
    causalRationale: 'Simultaneous salient motion creates competing orienting responses. Sequenced salience makes the intended reading order easier to infer and reduces visual search during change.',
    perceptualEffects: ['clear first-next-later order', 'reduced competition', 'stronger narrative continuity'],
    worksWhen: ['information has an intended temporal order', 'one state must establish context before another appears', 'a transition changes primary focus'],
    failsWhen: ['the task requires simultaneous comparison', 'every element animates with equal salience', 'handoffs are delayed enough to feel unresponsive'],
    creativeVariables: ['salience', 'onset offset', 'overlap', 'contrast', 'focus persistence'],
    failureModes: ['attention ping-pongs between competing motions', 'secondary motion steals the first fixation', 'late handoff feels like latency'],
    counterexamples: ['a monitoring interface where several independent signals must remain simultaneously visible'],
    diagnostics: ['identify the intended focus at each beat and verify only one dominant orienting cue exists', 'test whether the next focus is predictable before it moves'],
    transferablePrinciples: ['temporal salience should define an intentional focus sequence'],
    adaptationRules: ['write the attention sequence before choosing effects', 'preserve simultaneous visibility when the task demands comparison'],
    copyRisks: ['using staggered reveals mechanically even when no priority change exists']
  }),
  principle({
    id: 'temporal-hierarchy',
    title: 'Temporal hierarchy should mirror information hierarchy',
    definition: 'Timing, duration and motion weight should reflect the relative importance and consequence of the information or action being changed.',
    causalRationale: 'People infer importance partly from salience, persistence and temporal emphasis. Equal animation weight flattens hierarchy; disproportionate motion can falsely promote secondary content.',
    perceptualEffects: ['importance is legible through time', 'primary events receive temporal emphasis', 'secondary events remain subordinate'],
    worksWhen: ['different events have materially different importance', 'transitions need to reinforce an existing hierarchy', 'a primary decision must dominate a state change'],
    failsWhen: ['animation weight contradicts content priority', 'every component uses the same duration and amplitude', 'temporal emphasis is used to compensate for weak static hierarchy'],
    creativeVariables: ['duration', 'delay', 'amplitude', 'path length', 'settling time', 'motion count'],
    failureModes: ['secondary chrome becomes more dramatic than core content', 'uniform motion erases priority', 'oversized motion creates false importance'],
    counterexamples: ['a parity comparison where intentionally equal temporal treatment communicates equivalence'],
    diagnostics: ['rank product importance first, then compare the rank to motion weight', 'mute visual styling and test whether temporal order still communicates the intended hierarchy'],
    transferablePrinciples: ['temporal emphasis should be proportional to semantic importance and consequence'],
    adaptationRules: ['derive duration/amplitude hierarchy from product hierarchy before tuning aesthetics'],
    copyRisks: ['treating longer or larger motion as inherently better for important events']
  }),
  principle({
    id: 'anticipation',
    title: 'Anticipation should prepare meaningful change',
    definition: 'A brief pre-change cue can prepare perception for a consequential transition when the upcoming change would otherwise feel abrupt or causally opaque.',
    causalRationale: 'Preparation gives the perceptual system an early signal about direction, agency or impending state change, reducing surprise cost and strengthening cause-effect interpretation.',
    perceptualEffects: ['clearer causality', 'reduced abruptness', 'stronger sense of intention'],
    worksWhen: ['a consequential change needs preparation', 'direct manipulation accumulates intent before commitment', 'a reveal benefits from directional expectation'],
    failsWhen: ['anticipation delays routine input', 'the change is already obvious from direct manipulation', 'pre-motion becomes decorative recoil'],
    creativeVariables: ['lead time', 'counter-movement', 'compression', 'preload cue', 'input coupling'],
    failureModes: ['anticipation becomes latency', 'recoil feels cartoonish', 'every micro-action gets a preparatory flourish'],
    counterexamples: ['a frequently repeated command where immediate response is more important than expressive preparation'],
    diagnostics: ['measure whether anticipation clarifies what is about to happen', 'remove it from high-frequency actions and compare perceived responsiveness'],
    transferablePrinciples: ['prepare perception only when preparation clarifies a meaningful upcoming change'],
    adaptationRules: ['scale anticipation with consequence and ambiguity, not with aesthetic ambition'],
    copyRisks: ['importing character-animation anticipation literally into utility UI']
  }),
  principle({
    id: 'overlap-follow-through',
    title: 'Overlap can express dependency and residual energy',
    definition: 'Related elements may begin or finish at different times to communicate dependency, hierarchy or residual motion rather than moving as a rigid block.',
    causalRationale: 'Perfectly synchronized motion implies rigid coupling. Controlled phase offsets can reveal parent-child relationships, material response or attention sequence while preserving one causal event.',
    perceptualEffects: ['richer causal relationships', 'less mechanical simultaneity', 'clearer parent-secondary hierarchy'],
    worksWhen: ['components are causally related but not identical', 'secondary response should follow a primary event', 'material or spatial continuity benefits from residual settling'],
    failsWhen: ['offsets make the interface feel sluggish', 'independent delays imply false hierarchy', 'overlap destroys alignment needed for comparison'],
    creativeVariables: ['phase offset', 'overlap ratio', 'settling order', 'dependency depth'],
    failureModes: ['stagger becomes a canned list animation', 'trailing elements feel disconnected', 'long tails accumulate into latency'],
    counterexamples: ['a strict data refresh where simultaneous replacement communicates one atomic update'],
    diagnostics: ['name the dependency each phase offset communicates', 'remove offsets that have no causal or hierarchy explanation'],
    transferablePrinciples: ['phase difference should communicate dependency, hierarchy or residual energy'],
    adaptationRules: ['keep causal groups coherent even when their timings overlap'],
    copyRisks: ['using stagger as decoration rather than relationship']
  }),
  principle({
    id: 'holds-stillness',
    title: 'Stillness and holds are active temporal decisions',
    definition: 'Periods without movement create temporal punctuation, reading space and contrast that make subsequent motion more meaningful.',
    causalRationale: 'Continuous change normalizes salience and reduces event contrast. Stable intervals let perception settle, support reading and create a baseline against which meaningful change becomes obvious.',
    perceptualEffects: ['greater contrast for important motion', 'calmer reading states', 'clearer temporal punctuation'],
    worksWhen: ['users need inspection or reading time', 'motion should punctuate consequence', 'a sequence needs cadence rather than constant flow'],
    failsWhen: ['holds block interaction without adding comprehension', 'stillness hides system feedback', 'pause duration ignores user expertise or task frequency'],
    creativeVariables: ['hold duration', 'rest ratio', 'motion density', 'recovery time'],
    failureModes: ['cinematic pauses become friction', 'continuous ambient motion erases rest', 'missing feedback is mistaken for stillness'],
    counterexamples: ['a progress indicator where lack of any change would obscure ongoing system activity'],
    diagnostics: ['map explicit still moments beside motion moments', 'verify every hold supports reading, anticipation, emphasis or recovery'],
    transferablePrinciples: ['stillness creates the baseline that gives motion contrast and meaning'],
    adaptationRules: ['design rest states explicitly and separate stillness from missing feedback'],
    copyRisks: ['using long holds to mimic cinematic prestige']
  }),
  principle({
    id: 'rhythm-pacing',
    title: 'Rhythm emerges from differentiated temporal intervals',
    definition: 'A motion system gains character when durations, holds and transitions form a coherent cadence tied to task meaning rather than uniform timing.',
    causalRationale: 'Repeated interval relationships create expectation. Controlled variation can mark structural differences; arbitrary variation feels inconsistent and uniform timing makes unrelated events feel equivalent.',
    perceptualEffects: ['coherent temporal character', 'predictable progression', 'legible differentiation between event classes'],
    worksWhen: ['a product has recurring event classes', 'multi-step sequences need temporal structure', 'brand character can be expressed through restrained cadence'],
    failsWhen: ['rhythm overrides responsiveness', 'timing varies without semantic reason', 'all interactions are forced into one cinematic cadence'],
    creativeVariables: ['duration ratios', 'hold ratios', 'acceleration profile', 'repetition', 'syncopation'],
    failureModes: ['uniform 300ms timing flattens meaning', 'fashionable slow-fast timing becomes mannerism', 'rhythm creates unnecessary waiting'],
    counterexamples: ['direct manipulation where timing should track the user continuously rather than a preset cadence'],
    diagnostics: ['group events by meaning and compare their timing families', 'test expert repeated use for accumulated delay'],
    transferablePrinciples: ['cadence should arise from meaningful event relationships, not arbitrary duration variety'],
    adaptationRules: ['derive temporal families from product event classes and task frequency'],
    copyRisks: ['copying a recognizable brand cadence as a style signature']
  }),
  principle({
    id: 'continuity-vs-cut',
    title: 'Continuity and cuts communicate different relationships',
    definition: 'Continuous transformation implies identity or spatial relationship persists; a cut or replacement implies a meaningful break, chapter change or discontinuity.',
    causalRationale: 'Object continuity helps people track what became what. Abrupt replacement removes that tracking and can efficiently signal categorical change when continuity would be misleading.',
    perceptualEffects: ['preserved object identity when needed', 'clear chapter boundaries when discontinuity is intentional'],
    worksWhen: ['state identity should persist across change', 'spatial orientation matters', 'a true categorical break should feel decisive'],
    failsWhen: ['continuity falsely implies equivalence', 'morphing becomes spectacle', 'cuts destroy spatial orientation users need'],
    creativeVariables: ['identity persistence', 'shared anchors', 'cut timing', 'match points', 'transform path'],
    failureModes: ['everything morphs because it can', 'hard cuts make related states feel unrelated', 'continuity hides a major conceptual break'],
    counterexamples: ['a destructive reset where preserving visual continuity could understate the severity of the change'],
    diagnostics: ['ask whether the pre- and post-state should be perceived as the same object/system', 'choose continuity or cut based on that semantic answer'],
    transferablePrinciples: ['use continuous change for preserved relationship and discontinuity for meaningful breaks'],
    adaptationRules: ['bind continuity decisions to identity, orientation and narrative structure'],
    copyRisks: ['using morphs or match cuts as signature tricks without semantic need']
  }),
  principle({
    id: 'perceived-mass-inertia',
    title: 'Perceived mass should constrain acceleration and stopping',
    definition: 'Objects that are meant to feel heavy, consequential or spatially substantial should generally resist abrupt velocity changes more than light or ephemeral elements.',
    causalRationale: 'Visual systems borrow expectations from physical experience. Acceleration, deceleration and displacement shape inferred mass even without literal physics simulation.',
    perceptualEffects: ['coherent physical character', 'greater sense of weight or lightness', 'more believable spatial response'],
    worksWhen: ['material or spatial character matters', 'different object classes need distinct physical identities', 'direct manipulation benefits from weight cues'],
    failsWhen: ['simulated mass delays utility interactions', 'physical metaphor conflicts with product semantics', 'heavy easing is applied globally'],
    creativeVariables: ['acceleration', 'deceleration', 'travel distance', 'overshoot', 'settling time'],
    failureModes: ['heavy UI feels sluggish', 'light objects move with implausible inertia', 'physics character becomes toy-like'],
    counterexamples: ['a command palette whose primary requirement is immediate appearance regardless of material metaphor'],
    diagnostics: ['compare acceleration profile to intended material/semantic weight', 'verify physical character does not add avoidable input latency'],
    transferablePrinciples: ['acceleration and stopping behavior influence perceived mass'],
    adaptationRules: ['use perceptual mass selectively and subordinate it to interaction responsiveness'],
    copyRisks: ['treating spring presets as physical intelligence']
  }),
  principle({
    id: 'damping-settling',
    title: 'Settling behavior communicates stability',
    definition: 'The way motion loses energy after a change determines whether the resulting state feels stable, lively, soft, mechanical or unresolved.',
    causalRationale: 'Residual oscillation implies stored energy and lower damping; rapid finite settling implies control. People read these temporal signatures as material and behavioral character.',
    perceptualEffects: ['clear sense of completion', 'material character', 'confidence that a state has stabilized'],
    worksWhen: ['a direct manipulation needs visible recovery', 'material character is part of the concept', 'completion benefits from finite settling'],
    failsWhen: ['oscillation obscures the final state', 'routine controls bounce by default', 'settling time exceeds semantic value'],
    creativeVariables: ['damping ratio', 'oscillation count', 'settle threshold', 'residual amplitude'],
    failureModes: ['endless micro-bounce', 'overdamped motion feels dead', 'completion remains visually ambiguous'],
    counterexamples: ['a decisive editorial cut where no residual energy should be implied'],
    diagnostics: ['count visible reversals after the primary event', 'verify the final state becomes perceptually stable quickly enough for the task'],
    transferablePrinciples: ['energy decay communicates stability and material character'],
    adaptationRules: ['choose settling behavior from intended physical character and task frequency, not a default spring'],
    copyRisks: ['using recognizable spring signatures as brand identity']
  }),
  principle({
    id: 'elasticity-resistance',
    title: 'Elasticity should imply recoverable deformation or resistance',
    definition: 'Elastic motion is most coherent when it represents recoverable deformation, boundary resistance or stored energy rather than a generic playful bounce.',
    causalRationale: 'Stretch, compression and rebound imply a system can deform and return. Without a boundary or material logic, elasticity creates a physical claim the interface cannot explain.',
    perceptualEffects: ['tactile resistance', 'recoverable material character', 'clear boundary feedback'],
    worksWhen: ['dragging reaches a boundary', 'a surface is intentionally soft or elastic', 'stored energy has a meaningful interaction role'],
    failsWhen: ['rigid semantic objects stretch for decoration', 'bounce is used on every confirmation', 'elasticity undermines seriousness or precision'],
    creativeVariables: ['deformation amount', 'rebound', 'resistance curve', 'boundary distance'],
    failureModes: ['toy-like interaction', 'false affordance', 'excessive rebound masks completion'],
    counterexamples: ['a legal or financial approval action where playful deformation would weaken perceived precision'],
    diagnostics: ['identify what is supposedly deforming and why it should recover', 'reject elasticity when no material/boundary model exists'],
    transferablePrinciples: ['elastic response should correspond to recoverable deformation, resistance or stored energy'],
    adaptationRules: ['make elasticity local to the causal surface or boundary'],
    copyRisks: ['copying fashionable rubber-band motion independent of material logic']
  }),
  principle({
    id: 'spatial-path-directness',
    title: 'Motion paths should preserve spatial logic',
    definition: 'An element should travel along a path that makes its origin, destination and relationship to surrounding structure understandable.',
    causalRationale: 'Trajectory is evidence about spatial relationship. Arbitrary arcs or long travel can imply nonexistent depth, detours or object identity changes.',
    perceptualEffects: ['stronger spatial orientation', 'clear source-destination relationship', 'less unnecessary visual travel'],
    worksWhen: ['objects move between related containers or states', 'drag/drop or continuity needs spatial explanation', 'depth and layout transformations matter'],
    failsWhen: ['a direct replacement would be clearer', 'decorative paths create false spatial relationships', 'travel distance overwhelms content'],
    creativeVariables: ['path curvature', 'distance', 'depth change', 'anchor preservation', 'occlusion'],
    failureModes: ['orbiting/arc motion for spectacle', 'objects cross unrelated regions', 'mobile travel becomes excessive'],
    counterexamples: ['a deliberately discontinuous chapter transition where spatial continuity should be broken'],
    diagnostics: ['trace the path without styling and ask what relationship it communicates', 'verify path length remains appropriate on mobile'],
    transferablePrinciples: ['trajectory should communicate real spatial or semantic relationship'],
    adaptationRules: ['preserve anchors and shorten paths when viewport constraints change'],
    copyRisks: ['using signature bezier paths as decoration']
  }),
  principle({
    id: 'interaction-causality',
    title: 'Interactive motion must remain causally coupled to input',
    definition: 'Motion triggered by user action should make agency obvious through prompt response, continuous coupling where appropriate, and a legible commit/recovery phase.',
    causalRationale: 'Perceived agency depends on temporal contingency between action and response. Delayed or disconnected motion weakens the feeling that the user caused the change.',
    perceptualEffects: ['strong agency', 'clear action-response relationship', 'higher confidence in direct manipulation'],
    worksWhen: ['dragging, pressing, scrubbing or committing actions', 'gesture state needs feedback', 'a result should visibly follow a cause'],
    failsWhen: ['animation begins too late', 'response continues independently after user intent changes', 'decorative reaction hides actual state'],
    creativeVariables: ['input latency', 'coupling ratio', 'release behavior', 'commit threshold', 'interruptibility'],
    failureModes: ['motion feels canned instead of interactive', 'gesture cannot be interrupted', 'animation masks slow application state'],
    counterexamples: ['an autonomous background process whose progress is not caused by continuous user input'],
    diagnostics: ['test interruption, reversal and repeated input', 'separate immediate acknowledgement from slower state transition'],
    transferablePrinciples: ['temporal contingency and interruptibility communicate user agency'],
    adaptationRules: ['keep acknowledgement immediate even when a richer transition follows'],
    copyRisks: ['adding magnetic or cursor-follow behavior that invents false causality']
  }),
  principle({
    id: 'scroll-choreography',
    title: 'Scroll should reveal structure, not seize control',
    definition: 'Scroll-linked motion should use the user-controlled progression to clarify spatial, narrative or comparative relationships while preserving navigation agency.',
    causalRationale: 'Scroll already represents intentional progression through content. Mapping meaningful relationships to that progression can strengthen comprehension; hijacking it or adding unrelated motion creates motor and attention conflict.',
    perceptualEffects: ['progressive disclosure', 'spatial continuity across sections', 'user-controlled pacing'],
    worksWhen: ['progress through content has a meaningful sequence', 'before/after or layered relationships benefit from scrubbing', 'spatial narrative is central'],
    failsWhen: ['scroll becomes a forced timeline', 'reading speed conflicts with animation requirements', 'mobile/touch behavior is fragile'],
    creativeVariables: ['scroll mapping', 'pin duration', 'scrub range', 'content density', 'release points'],
    failureModes: ['scroll-jacking', 'long pinned dead zones', 'animation prevents rapid navigation', 'mobile mismatch'],
    counterexamples: ['a utility page where users frequently jump directly to known controls'],
    diagnostics: ['disable linked motion and verify content remains navigable', 'test fast scroll, reverse scroll and touch momentum'],
    transferablePrinciples: ['scroll-linked motion should clarify progression while preserving user pacing and escape'],
    adaptationRules: ['treat scroll as input, not as an excuse for a linear film', 'provide simpler mobile reinterpretation when needed'],
    copyRisks: ['reproducing fashionable pinned-scroll sequences regardless of content structure']
  }),
  principle({
    id: 'camera-reveal-framing',
    title: 'Camera movement should change understanding of space or focus',
    definition: 'Virtual camera movement is justified when reframing, reveal, parallax or viewpoint change communicates spatial structure, scale, relationship or narrative focus.',
    causalRationale: 'Changing viewpoint is a high-salience operation that alters perceived spatial relations. When nothing meaningful is learned from the new view, camera motion becomes expensive spectacle.',
    perceptualEffects: ['spatial reveal', 'controlled focus', 'sense of scale and continuity'],
    worksWhen: ['depth is materially relevant', 'a reveal depends on occlusion or viewpoint', 'narrative focus shifts through space'],
    failsWhen: ['camera motion exists only because 3D is available', 'large viewpoint change harms orientation', 'camera movement competes with reading or induces discomfort'],
    creativeVariables: ['framing', 'focal target', 'camera path', 'field of view', 'parallax', 'occlusion'],
    failureModes: ['fly-through spectacle', 'unmotivated orbit', 'loss of orientation', 'vestibular discomfort'],
    counterexamples: ['a flat data table where viewpoint change adds no spatial meaning'],
    diagnostics: ['state what new relationship becomes visible because the camera moved', 'compare against a static reframe'],
    transferablePrinciples: ['move the camera only when viewpoint change communicates space, scale, reveal or focus'],
    adaptationRules: ['prefer reframing or object motion when camera travel adds no unique information'],
    copyRisks: ['treating cinematic camera motion as synonymous with premium design']
  }),
  principle({
    id: 'editing-temporal-compression',
    title: 'Editing can compress or separate time deliberately',
    definition: 'Cuts, matches, skips and temporal compression can remove unimportant intermediate states or mark meaningful chapters without pretending every change is continuous.',
    causalRationale: 'Not every intermediate state carries useful information. Editing controls which temporal relationships remain visible, allowing faster progression while preserving the important causal or narrative landmarks.',
    perceptualEffects: ['faster progression', 'clear chaptering', 'focus on meaningful temporal landmarks'],
    worksWhen: ['intermediate motion adds no comprehension', 'a process has clear semantic beats', 'a categorical change should be decisive'],
    failsWhen: ['removed states are needed for orientation', 'cuts obscure cause and effect', 'rapid editing increases cognitive load'],
    creativeVariables: ['cut point', 'match anchor', 'beat spacing', 'temporal skip', 'transition overlap'],
    failureModes: ['hyperactive montage', 'missing causal steps', 'chapter changes feel arbitrary'],
    counterexamples: ['direct manipulation where continuous visual feedback is necessary to preserve agency'],
    diagnostics: ['list which temporal information is removed and why it is nonessential', 'verify a user can still reconstruct cause, state and orientation'],
    transferablePrinciples: ['temporal compression should remove low-value time while preserving meaningful landmarks'],
    adaptationRules: ['retain continuity for agency/orientation and cut when discontinuity is semantically useful'],
    copyRisks: ['copying film-editing gestures as visual flair without information structure']
  }),
  principle({
    id: 'typographic-motion',
    title: 'Typographic motion must preserve language hierarchy and legibility',
    definition: 'Animated type should use temporal behavior to clarify reading order, semantic emphasis or structural transformation without degrading recognition and reading.',
    causalRationale: 'Text is both visual form and language. Motion that fragments glyphs or words competes with lexical processing unless the temporal transformation itself carries meaning.',
    perceptualEffects: ['temporal emphasis in language', 'controlled reading order', 'expressive but legible typographic hierarchy'],
    worksWhen: ['headline emphasis or chapter transition has semantic value', 'text changes role or hierarchy', 'kinetic language is part of the communication'],
    failsWhen: ['body copy becomes animated ornament', 'letters split without meaning', 'motion delays access to required content'],
    creativeVariables: ['unit of motion', 'reading order', 'masking', 'baseline stability', 'duration', 'contrast'],
    failureModes: ['split-text cliché', 'illegible glyph deformation', 'stagger delays reading', 'motion fights typography'],
    counterexamples: ['dense instructional copy where stable reading is the dominant requirement'],
    diagnostics: ['read the text at normal task speed with animation enabled', 'identify the linguistic or hierarchy meaning added by temporal treatment'],
    transferablePrinciples: ['typographic motion should support language meaning and hierarchy before visual spectacle'],
    adaptationRules: ['keep long-form reading stable; concentrate kinetic treatment on semantically justified moments'],
    copyRisks: ['reproducing recognizable kinetic-type signatures or generic split-text effects']
  }),
  principle({
    id: 'image-motion',
    title: 'Image motion should preserve subject and compositional intent',
    definition: 'Movement inside or around imagery should clarify focus, depth, transition or narrative relation without destroying crop, subject integrity or photographic composition.',
    causalRationale: 'Images already encode strong visual hierarchy. Camera-like crops, pans, masks or depth shifts can redirect attention, but arbitrary motion can undermine the composition that made the image effective.',
    perceptualEffects: ['controlled subject emphasis', 'depth or narrative connection', 'preserved image hierarchy'],
    worksWhen: ['subject focus needs temporal emphasis', 'two images have a meaningful transition relationship', 'depth extraction supports composition'],
    failsWhen: ['Ken Burns movement is applied by default', 'subject is cropped or distorted during responsive motion', 'parallax creates false spatial structure'],
    creativeVariables: ['crop', 'subject anchor', 'pan distance', 'mask', 'depth separation', 'focal continuity'],
    failureModes: ['generic slow zoom', 'subject leaves safe crop', 'depth effect contradicts image'],
    counterexamples: ['an evidence image that must remain spatially stable for inspection and comparison'],
    diagnostics: ['track the subject anchor through every viewport and temporal state', 'compare moving treatment to the original compositional hierarchy'],
    transferablePrinciples: ['image motion should remain subordinate to subject, crop and compositional meaning'],
    adaptationRules: ['bind motion to subject anchors and responsive crop rules'],
    copyRisks: ['using familiar cinematic zoom/parallax treatments as default sophistication']
  }),
  principle({
    id: 'material-motion',
    title: 'Material motion should follow an explicit material model',
    definition: 'Deformation, flow, refraction, grain, light response or surface movement should be governed by an intended material behavior rather than arbitrary visual noise.',
    causalRationale: 'Consistent response lets viewers infer material qualities and creates coherent expectations. Inconsistent response makes the surface feel like an effect layer rather than a material system.',
    perceptualEffects: ['coherent material character', 'predictable response', 'stronger world consistency'],
    worksWhen: ['materiality is part of the art direction', 'surface response communicates interaction or state', 'ambient material behavior has a bounded role'],
    failsWhen: ['material simulation has no conceptual role', 'noise dominates content', 'expensive shaders exist only as technical display'],
    creativeVariables: ['viscosity', 'roughness cue', 'deformation', 'light response', 'noise scale', 'flow direction'],
    failureModes: ['shader demo aesthetic', 'material behavior changes arbitrarily by section', 'ambient movement never rests'],
    counterexamples: ['a precise utilitarian product surface whose meaning depends on visual stability rather than material expression'],
    diagnostics: ['describe the implied material in plain physical terms', 'verify each motion variable follows that material model and project meaning'],
    transferablePrinciples: ['material motion should be coherent with an explicit material model and project role'],
    adaptationRules: ['separate material intent from implementation technology such as shaders or WebGL'],
    copyRisks: ['copying trendy liquid, grain or iridescent effects without project-specific material logic']
  }),
  principle({
    id: 'procedural-generative-motion',
    title: 'Procedural motion needs bounded rules and readable invariants',
    definition: 'Generative or procedural motion should vary within a constrained system whose stable relationships remain perceptible and tied to the concept.',
    causalRationale: 'Variation creates richness, but unconstrained randomness erodes identity and predictability. Readable invariants let a generative system feel authored rather than arbitrary.',
    perceptualEffects: ['living variation', 'authored complexity', 'repeatable system identity'],
    worksWhen: ['variation itself has conceptual value', 'ambient behavior benefits from non-repetition', 'a system must scale to many states while preserving grammar'],
    failsWhen: ['randomness competes with task attention', 'rules cannot be explained', 'variation causes unstable hierarchy or performance'],
    creativeVariables: ['seed', 'bounds', 'frequency', 'amplitude', 'attractor rules', 'state coupling'],
    failureModes: ['screensaver behavior', 'non-deterministic proof', 'random hierarchy', 'unbounded CPU/GPU cost'],
    counterexamples: ['a deterministic approval transition that must look and behave identically for auditability'],
    diagnostics: ['name the invariants that remain stable across seeds', 'run multiple seeds and inspect hierarchy/accessibility/performance bounds'],
    transferablePrinciples: ['generative richness requires stable invariants and bounded variation'],
    adaptationRules: ['make randomness subordinate to semantic state, hierarchy and deterministic proof requirements'],
    copyRisks: ['mistaking noise fields or particles for original creative reasoning']
  }),
  principle({
    id: 'responsive-reinterpretation',
    title: 'Responsive motion should be re-authored, not scaled',
    definition: 'Motion behavior should preserve semantic purpose across viewport, input and density changes even when paths, depth, timing or constructs must change.',
    causalRationale: 'Mobile changes available space, touch mechanics, visibility and performance. Geometrically scaling desktop motion can increase travel, occlusion, latency or gesture conflict while preserving none of its original benefit.',
    perceptualEffects: ['consistent meaning across devices', 'appropriate travel and pacing', 'preserved hierarchy under constraint'],
    worksWhen: ['the same product meaning appears across desktop/mobile', 'motion depends on layout geometry', 'input mode changes from pointer to touch'],
    failsWhen: ['desktop travel is merely reduced by a percentage', 'touch gestures conflict with scroll', 'mobile motion preserves spectacle but loses meaning'],
    creativeVariables: ['path length', 'depth', 'timing', 'gesture mapping', 'occlusion', 'viewport density'],
    failureModes: ['tiny desktop choreography on mobile', 'large off-screen travel', 'pointer-only behavior', 'mobile performance collapse'],
    counterexamples: ['a small self-contained control whose geometry and input behavior are effectively identical across viewports'],
    diagnostics: ['state the semantic invariant, then separately author desktop and mobile behavior', 'test touch, orientation and narrow viewport evidence'],
    transferablePrinciples: ['preserve motion meaning, not literal geometry, across responsive contexts'],
    adaptationRules: ['shorten travel, reduce depth and change constructs when mobile constraints require it'],
    copyRisks: ['treating responsive motion as uniform duration/scale reduction']
  }),
  principle({
    id: 'reduced-motion-equivalence',
    title: 'Reduced motion requires semantic equivalence',
    definition: 'A reduced-motion mode should preserve the hierarchy, state change, causality and orientation communicated by motion using lower-motion temporal or static alternatives.',
    causalRationale: 'Removing animation without replacing its informational role can delete meaning. Equivalent cues such as immediate re-layout, contrast, focus, opacity or explicit state labels can preserve comprehension while reducing motion exposure.',
    perceptualEffects: ['preserved meaning with lower motion exposure', 'clear state transitions', 'accessible hierarchy'],
    worksWhen: ['motion carries state or hierarchy information', 'user preference requests reduced motion', 'large travel/zoom/parallax would be uncomfortable'],
    failsWhen: ['reduced mode simply disables everything', 'important causality disappears', 'opacity-only replacement still creates problematic repeated flicker'],
    creativeVariables: ['travel removal', 'duration', 'opacity', 'focus', 'contrast', 'state labeling'],
    failureModes: ['semantic loss', 'hidden completion', 'inaccessible orientation', 'reduced mode becomes visually broken'],
    counterexamples: ['a decorative ambient effect that can be removed entirely because it carries no required meaning'],
    diagnostics: ['compare the questions a user can answer in full-motion and reduced-motion modes', 'verify state, hierarchy and action consequence remain equally clear'],
    transferablePrinciples: ['reduce motion exposure while preserving the information motion communicated'],
    adaptationRules: ['replace temporal travel with stable hierarchy, contrast, focus or immediate state changes as needed'],
    copyRisks: ['equating reduced motion with a blanket animation-off switch']
  }),
  principle({
    id: 'vestibular-safety',
    title: 'Large-field motion carries vestibular cost',
    definition: 'Zoom, rotation, parallax, large translation and camera motion across substantial visual field area require stronger justification and safer alternatives than local small-scale motion.',
    causalRationale: 'Large-field visual motion can create a mismatch between visual and vestibular cues for susceptible users, while also consuming high attention. Local motion generally creates lower exposure.',
    perceptualEffects: ['safer motion exposure', 'more deliberate use of camera/large-field movement'],
    worksWhen: ['large movement is semantically necessary and reduced-motion alternatives exist', 'exposure is brief and controlled'],
    failsWhen: ['background continuously drifts', 'scroll creates large parallax or zoom', 'camera rotation is decorative', 'no alternative exists'],
    creativeVariables: ['field coverage', 'velocity', 'acceleration', 'depth/zoom', 'rotation', 'exposure duration'],
    failureModes: ['motion sickness risk', 'fatigue', 'attention capture unrelated to task'],
    counterexamples: ['a local button state change confined to a small area with no large-field movement'],
    diagnostics: ['estimate visual-field coverage and movement class', 'test reduced-motion path and eliminate unnecessary camera/background motion'],
    transferablePrinciples: ['the larger and more camera-like the motion, the higher the accessibility justification burden'],
    adaptationRules: ['prefer local object/state changes over large-field motion when both communicate the same meaning'],
    copyRisks: ['using sweeping camera motion because it reads as cinematic']
  }),
  principle({
    id: 'performance-value',
    title: 'Motion complexity must earn render and interaction cost',
    definition: 'The complexity of a motion construct should be proportional to the unique creative/semantic value it provides beyond a simpler implementation.',
    causalRationale: 'Complex motion can increase CPU/GPU work, bundle weight, memory, latency, instability and QA surface. If a simpler construct communicates the same meaning, extra complexity reduces product quality rather than increasing sophistication.',
    perceptualEffects: ['more reliable interaction', 'fewer dropped frames', 'creative complexity concentrated where it matters'],
    worksWhen: ['complexity enables otherwise impossible spatial/material/temporal meaning', 'performance evidence stays within budget', 'fallbacks preserve meaning'],
    failsWhen: ['technology is chosen before behavior', 'a shader/3D stack adds no unique semantic value', 'effects degrade interaction responsiveness'],
    creativeVariables: ['layer count', 'animated area', 'layout/paint cost', 'GPU complexity', 'asset weight', 'duration', 'concurrency'],
    failureModes: ['jank', 'thermal/battery cost', 'slow startup', 'motion disabled on weaker devices with no semantic fallback'],
    counterexamples: ['a genuinely spatial interaction where 3D geometry is the simplest faithful model of the required behavior'],
    diagnostics: ['describe the simplest sufficient motion model first', 'state what unique value each added layer of complexity buys', 'measure actual runtime evidence before production readiness'],
    transferablePrinciples: ['choose the cheapest sufficient motion model that preserves creative intent'],
    adaptationRules: ['separate creative intent from GSAP/Three.js/WebGL/Rive/Blender implementation choice'],
    copyRisks: ['equating technical complexity with creative quality']
  }),
  principle({
    id: 'motion-genericity-critique',
    title: 'Motion quality requires project-specific rejection rules',
    definition: 'A motion direction becomes more ownable when it can explain not only what it does, but which familiar motion habits it refuses and why those habits would weaken this project.',
    causalRationale: 'Category conventions and fashionable effects are easy defaults. Explicit rejection criteria force comparison against project truth, making genericity visible before it becomes implementation.',
    perceptualEffects: ['stronger project character', 'less fashionable sameness', 'clearer taste boundary'],
    worksWhen: ['multiple plausible motion languages exist', 'a category has strong default aesthetics', 'references could pull the work toward imitation'],
    failsWhen: ['anti-patterns become novelty for its own sake', 'familiar conventions are rejected despite usability value', 'rejection rules are vague aesthetic dislikes'],
    creativeVariables: ['category convention', 'project truth', 'recognition need', 'novelty', 'appropriateness'],
    failureModes: ['Awwwards imitation', 'anti-conventional gimmicks', 'generic premium motion', 'novelty outruns usability'],
    counterexamples: ['a convention-dominant control where familiar behavior materially improves recognition and predictability'],
    diagnostics: ['name at least two tempting category-default motion patterns and test them against project meaning', 'ask whether a competitor could reuse the motion unchanged'],
    transferablePrinciples: ['ownability grows from project-specific causal choices and explicit rejection of irrelevant defaults'],
    adaptationRules: ['preserve useful conventions where recognition matters; reject generic expression, not usability itself'],
    copyRisks: ['treating novelty or Awwwards aesthetics as evidence of originality']
  }),
  principle({
    id: 'narrative-timing',
    title: 'Narrative timing should expose consequence in meaningful beats',
    definition: 'When an experience has a beginning, development and consequence, motion should organize those changes into beats that correspond to what the user needs to understand at each stage.',
    causalRationale: 'Temporal grouping helps people segment continuous experience into events. Beat boundaries tied to semantic change support comprehension; arbitrary theatrical beats add ceremony without information.',
    perceptualEffects: ['clear progression', 'stronger expectation and resolution', 'legible cause-consequence sequence'],
    worksWhen: ['a multi-step decision or reveal has semantic stages', 'product state evolves through meaningful phases', 'storytelling is appropriate to the task'],
    failsWhen: ['routine actions are forced into a story arc', 'beats delay access to controls', 'dramatic climax exaggerates trivial events'],
    creativeVariables: ['beat count', 'beat duration', 'reveal order', 'resolution timing', 'narrative compression'],
    failureModes: ['over-directed product experience', 'ceremony fatigue', 'meaningless climax'],
    counterexamples: ['a repetitive expert workflow where users need immediate direct access rather than staged progression'],
    diagnostics: ['write each beat as a semantic sentence and remove any beat that adds no new understanding'],
    transferablePrinciples: ['temporal beats should correspond to meaningful changes in understanding or consequence'],
    adaptationRules: ['compress or remove narrative beats for high-frequency utility interactions'],
    copyRisks: ['importing film-trailer pacing into routine interface behavior']
  }),
  principle({
    id: 'motion-interruptibility',
    title: 'Motion should yield to new intent',
    definition: 'Interactive transitions should define how they are interrupted, reversed, retargeted or completed when new user or system input arrives.',
    causalRationale: 'Interfaces are not fixed films. When new intent arrives during motion, a rigid animation can temporarily take control away from the user or leave state and visuals out of sync.',
    perceptualEffects: ['stronger responsiveness', 'continuous agency', 'less state-motion mismatch'],
    worksWhen: ['users can repeat, reverse or redirect actions', 'navigation can change before transitions finish', 'live state can update asynchronously'],
    failsWhen: ['animation locks input', 'reversal restarts from the wrong state', 'visual state completes after underlying state changed'],
    creativeVariables: ['interrupt point', 'retargeting', 'velocity continuity', 'state reconciliation', 'cancel behavior'],
    failureModes: ['input lockout', 'snap-back', 'double transitions', 'stale visual state'],
    counterexamples: ['a short noninteractive export animation that simply reflects an already committed immutable state'],
    diagnostics: ['trigger opposite/new actions at multiple points in the transition', 'verify visual and application state reconcile deterministically'],
    transferablePrinciples: ['interactive motion must define behavior under interruption and new intent'],
    adaptationRules: ['preserve current state/velocity where useful and prioritize latest valid intent over animation completion'],
    copyRisks: ['treating authored sequences as uninterruptible films inside interactive products']
  }),
  principle({
    id: 'motion-state-legibility',
    title: 'The terminal state must be more legible than the transition',
    definition: 'Motion should resolve into a stable state whose meaning, hierarchy and affordances remain clear after the transition ends.',
    causalRationale: 'Transitions are temporary; users act on terminal states. A visually impressive transition that lands in ambiguous hierarchy or lingering motion sacrifices task comprehension for spectacle.',
    perceptualEffects: ['clear completion', 'stable post-transition hierarchy', 'lower uncertainty'],
    worksWhen: ['motion connects actionable states', 'users must immediately inspect or act after transition'],
    failsWhen: ['ambient motion continues to obscure completion', 'settling shifts controls after they become actionable', 'terminal hierarchy depends on remembering the transition'],
    creativeVariables: ['settle time', 'terminal contrast', 'focus', 'motion tail', 'action readiness'],
    failureModes: ['moving target after completion', 'unclear final state', 'transition carries information not represented after it ends'],
    counterexamples: ['a purely expressive noninteractive brand film where there is no actionable terminal UI state'],
    diagnostics: ['pause on the terminal frame and verify state/priority/affordance without temporal memory', 'measure when controls become stable and actionable'],
    transferablePrinciples: ['temporary motion should resolve into a self-sufficient stable state'],
    adaptationRules: ['stop or subordinate residual motion before the user needs to inspect or act'],
    copyRisks: ['optimizing the transition while neglecting the landed product state']
  }),
  principle({
    id: 'motion-cross-modal-consistency',
    title: 'Motion character should agree with the wider creative world',
    definition: 'Temporal behavior should reinforce the project’s typography, composition, material, interaction and narrative logic rather than introduce a separate fashionable personality.',
    causalRationale: 'People form expectations across modalities. If typography is precise and restrained while motion is elastic and playful, the system communicates competing characters unless the contrast is deliberate and justified.',
    perceptualEffects: ['coherent creative world', 'stronger authored character', 'fewer contradictory cues'],
    worksWhen: ['the project already has an approved Creative World', 'motion is one expression of a broader design language'],
    failsWhen: ['motion is designed from an isolated reference reel', 'physical character contradicts material language', 'timing contradicts typographic/compositional rhythm'],
    creativeVariables: ['rhythm', 'mass', 'transition grammar', 'spatial behavior', 'typographic behavior', 'material response'],
    failureModes: ['motion feels bolted on', 'different pages imply different personalities', 'motion trend overrides product identity'],
    counterexamples: ['a deliberate counterpoint where motion is intentionally used to create tension against otherwise static visual language and the rationale is explicit'],
    diagnostics: ['compare motion thesis to Creative World motion/material/interaction/composition statements', 'name every intentional cross-modal contradiction'],
    transferablePrinciples: ['motion is part of the creative world and should reinforce or deliberately counterpoint its other systems'],
    adaptationRules: ['ground motion choices in selected Creative World decisions before referencing external motion patterns'],
    copyRisks: ['letting a motion reference become a second art direction']
  })
]);

export function buildMotionIntelligenceV2Foundation() {
  return buildCreativeIntelligenceFoundation({ entries: MOTION_INTELLIGENCE_V2_KNOWLEDGE });
}
